spring:
  application:
    name: DigitalPortfolio
  datasource:
    url: jdbc:mysql://localhost:3306/digital_portfolio_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect